import { connect, connection } from 'mongoose';
import { config } from 'dotenv';

config();

// Define schemas inline for seed script
const categoryData = [
  { name: 'Gundam', slug: 'gundam' },
  { name: 'Anime Figure', slug: 'anime-figure' },
  { name: 'Scale Figure', slug: 'scale-figure' },
  { name: 'Nendoroid', slug: 'nendoroid' },
  { name: 'Figma', slug: 'figma' },
  { name: 'Model Kit', slug: 'model-kit' },
];

const productData = [
  // Gundam Products
  {
    name: 'MG Gundam Barbatos',
    slug: 'mg-gundam-barbatos',
    sku: 'GD-001',
    price: 820000,
    originalPrice: 950000,
    isOnSale: true,
    thumbnail: 'https://res.cloudinary.com/demo/image/upload/v1/gundam_barbatos.jpg',
    images: [
      'https://res.cloudinary.com/demo/image/upload/v1/gundam_barbatos_1.jpg',
      'https://res.cloudinary.com/demo/image/upload/v1/gundam_barbatos_2.jpg',
    ],
    stock: 15,
    inStock: true,
    rating: 4.8,
    reviewCount: 127,
    soldCount: 342,
    brand: 'Bandai',
    series: 'Gundam Iron-Blooded Orphans',
    character: 'Gundam Barbatos',
    material: 'Plastic',
    height: '18cm',
    scale: '1/100',
    shortDescription: 'Master Grade Gundam Barbatos from Iron-Blooded Orphans',
    description: 'The main mobile suit from Gundam: Iron-Blooded Orphans now available as a Master Grade kit. Features excellent articulation, detailed inner frame, and various weapons.',
    tags: ['gundam', 'mecha', 'bandai', 'mg'],
    isHot: true,
    isFeatured: true,
  },
  {
    name: 'RG Nu Gundam',
    slug: 'rg-nu-gundam',
    sku: 'GD-002',
    price: 1250000,
    originalPrice: 1450000,
    isOnSale: true,
    thumbnail: 'https://res.cloudinary.com/demo/image/upload/v1/nu_gundam.jpg',
    images: [
      'https://res.cloudinary.com/demo/image/upload/v1/nu_gundam_1.jpg',
      'https://res.cloudinary.com/demo/image/upload/v1/nu_gundam_2.jpg',
    ],
    stock: 8,
    inStock: true,
    rating: 5.0,
    reviewCount: 203,
    soldCount: 456,
    brand: 'Bandai',
    series: "Gundam Char's Counterattack",
    character: 'Nu Gundam',
    material: 'Plastic',
    height: '16cm',
    scale: '1/144',
    shortDescription: 'Real Grade Nu Gundam with full psycho-frame',
    description: 'The legendary Nu Gundam in Real Grade format. Features full psycho-frame inner structure, Fin Funnel system, and beam rifle.',
    tags: ['gundam', 'rg', 'bandai', 'psycho-frame'],
    isHot: true,
    isFeatured: true,
  },
  {
    name: 'HGUC Zaku II',
    slug: 'hguc-zaku-ii',
    sku: 'GD-003',
    price: 480000,
    originalPrice: 550000,
    isOnSale: true,
    thumbnail: 'https://res.cloudinary.com/demo/image/upload/v1/zaku_ii.jpg',
    images: ['https://res.cloudinary.com/demo/image/upload/v1/zaku_ii_1.jpg'],
    stock: 25,
    inStock: true,
    rating: 4.5,
    reviewCount: 89,
    soldCount: 234,
    brand: 'Bandai',
    series: 'Mobile Suit Gundam',
    character: 'Zaku II',
    material: 'Plastic',
    height: '12cm',
    scale: '1/144',
    shortDescription: 'High Grade Universal Century Zaku II',
    description: 'Classic Zeon mobile suit in High Grade format. Great for beginners and customization.',
    tags: ['gundam', 'hg', 'zeon', 'classic'],
    isHot: false,
    isFeatured: false,
  },

  // Anime Figures
  {
    name: 'Miku Hatsune Racing Ver. 2023',
    slug: 'miku-hatsune-racing-2023',
    sku: 'AF-001',
    price: 2150000,
    originalPrice: 2450000,
    isOnSale: true,
    thumbnail: 'https://res.cloudinary.com/demo/image/upload/v1/miku_racing.jpg',
    images: [
      'https://res.cloudinary.com/demo/image/upload/v1/miku_racing_1.jpg',
      'https://res.cloudinary.com/demo/image/upload/v1/miku_racing_2.jpg',
    ],
    stock: 5,
    inStock: true,
    rating: 4.9,
    reviewCount: 312,
    soldCount: 567,
    brand: 'Good Smile Company',
    series: 'Vocaloid',
    character: 'Hatsune Miku',
    material: 'PVC, ABS',
    height: '24cm',
    scale: '1/7',
    shortDescription: 'Miku Hatsune in stunning racing queen outfit',
    description: 'Beautifully sculpted figure of Hatsune Miku in her Racing 2023 outfit. Premium quality with vibrant colors and detailed base.',
    tags: ['miku', 'vocaloid', 'racing', 'gsc'],
    isHot: true,
    isFeatured: true,
  },
  {
    name: 'Rem Crystal Dress Ver.',
    slug: 'rem-crystal-dress',
    sku: 'AF-002',
    price: 1850000,
    originalPrice: 2100000,
    isOnSale: true,
    thumbnail: 'https://res.cloudinary.com/demo/image/upload/v1/rem_crystal.jpg',
    images: ['https://res.cloudinary.com/demo/image/upload/v1/rem_crystal_1.jpg'],
    stock: 10,
    inStock: true,
    rating: 4.7,
    reviewCount: 156,
    soldCount: 289,
    brand: 'Furyu',
    series: 'Re:Zero',
    character: 'Rem',
    material: 'PVC',
    height: '22cm',
    scale: '1/7',
    shortDescription: 'Rem in elegant crystal wedding dress',
    description: 'Stunning figure of Rem wearing a beautiful crystal wedding dress. Features transparent elements and detailed sculpting.',
    tags: ['rem', 'rezero', 'wedding', 'furyu'],
    isHot: true,
    isFeatured: false,
  },
  {
    name: 'Asuna Undine Ver.',
    slug: 'asuna-undine',
    sku: 'AF-003',
    price: 1650000,
    originalPrice: 1850000,
    isOnSale: true,
    thumbnail: 'https://res.cloudinary.com/demo/image/upload/v1/asuna_undine.jpg',
    images: ['https://res.cloudinary.com/demo/image/upload/v1/asuna_undine_1.jpg'],
    stock: 12,
    inStock: true,
    rating: 4.6,
    reviewCount: 98,
    soldCount: 178,
    brand: 'Alter',
    series: 'Sword Art Online',
    character: 'Asuna',
    material: 'PVC, ABS',
    height: '20cm',
    scale: '1/8',
    shortDescription: 'Asuna in Undine avatar outfit',
    description: 'Beautifully detailed figure of Asuna in her ALO Undine outfit with translucent wings.',
    tags: ['asuna', 'sao', 'alo', 'alter'],
    isHot: false,
    isFeatured: true,
  },

  // Nendoroids
  {
    name: 'Nendoroid Gojo Satoru',
    slug: 'nendoroid-gojo-satoru',
    sku: 'ND-001',
    price: 850000,
    originalPrice: 950000,
    isOnSale: true,
    thumbnail: 'https://res.cloudinary.com/demo/image/upload/v1/nendo_gojo.jpg',
    images: ['https://res.cloudinary.com/demo/image/upload/v1/nendo_gojo_1.jpg'],
    stock: 18,
    inStock: true,
    rating: 4.8,
    reviewCount: 245,
    soldCount: 512,
    brand: 'Good Smile Company',
    series: 'Jujutsu Kaisen',
    character: 'Gojo Satoru',
    material: 'ABS, PVC',
    height: '10cm',
    scale: 'Non-scale',
    shortDescription: 'Adorable Nendoroid of the strongest sorcerer',
    description: "Nendoroid of Gojo Satoru from Jujutsu Kaisen. Comes with multiple face plates, hands, and Infinity effect parts.",
    tags: ['nendoroid', 'gojo', 'jjk', 'chibi'],
    isHot: true,
    isFeatured: true,
  },
  {
    name: 'Nendoroid Nezuko Kamado',
    slug: 'nendoroid-nezuko',
    sku: 'ND-002',
    price: 780000,
    originalPrice: 880000,
    isOnSale: true,
    thumbnail: 'https://res.cloudinary.com/demo/image/upload/v1/nendo_nezuko.jpg',
    images: ['https://res.cloudinary.com/demo/image/upload/v1/nendo_nezuko_1.jpg'],
    stock: 22,
    inStock: true,
    rating: 4.9,
    reviewCount: 389,
    soldCount: 678,
    brand: 'Good Smile Company',
    series: 'Demon Slayer',
    character: 'Nezuko Kamado',
    material: 'ABS, PVC',
    height: '10cm',
    scale: 'Non-scale',
    shortDescription: 'Cute Nendoroid of everyones favorite demon',
    description: 'Nendoroid of Nezuko with bamboo muzzle, flame effects, and multiple expressions.',
    tags: ['nendoroid', 'nezuko', 'kimetsu', 'demon-slayer'],
    isHot: true,
    isFeatured: false,
  },
  {
    name: 'Nendoroid Chainsaw Man',
    slug: 'nendoroid-chainsaw-man',
    sku: 'ND-003',
    price: 820000,
    originalPrice: 0,
    isOnSale: false,
    thumbnail: 'https://res.cloudinary.com/demo/image/upload/v1/nendo_denji.jpg',
    images: ['https://res.cloudinary.com/demo/image/upload/v1/nendo_denji_1.jpg'],
    stock: 15,
    inStock: true,
    rating: 4.7,
    reviewCount: 167,
    soldCount: 234,
    brand: 'Good Smile Company',
    series: 'Chainsaw Man',
    character: 'Denji',
    material: 'ABS, PVC',
    height: '10cm',
    scale: 'Non-scale',
    shortDescription: 'Nendoroid of the chainsaw devil hybrid',
    description: 'Denji in Nendoroid form with chainsaw head and battle effects.',
    tags: ['nendoroid', 'denji', 'chainsaw-man', 'csm'],
    isHot: false,
    isFeatured: false,
  },

  // Figma
  {
    name: 'Figma Saber Alter',
    slug: 'figma-saber-alter',
    sku: 'FG-001',
    price: 1150000,
    originalPrice: 1300000,
    isOnSale: true,
    thumbnail: 'https://res.cloudinary.com/demo/image/upload/v1/figma_saber.jpg',
    images: ['https://res.cloudinary.com/demo/image/upload/v1/figma_saber_1.jpg'],
    stock: 8,
    inStock: true,
    rating: 4.8,
    reviewCount: 178,
    soldCount: 298,
    brand: 'Max Factory',
    series: 'Fate/stay night',
    character: 'Saber Alter',
    material: 'ABS, PVC',
    height: '14cm',
    scale: 'Non-scale',
    shortDescription: 'Highly poseable Figma of the corrupted king',
    description: 'Figma Saber Alter with Excalibur Morgan, multiple expressions and hands.',
    tags: ['figma', 'saber', 'fate', 'articulated'],
    isHot: false,
    isFeatured: true,
  },
  {
    name: 'Figma Tanjiro Kamado',
    slug: 'figma-tanjiro',
    sku: 'FG-002',
    price: 980000,
    originalPrice: 1100000,
    isOnSale: true,
    thumbnail: 'https://res.cloudinary.com/demo/image/upload/v1/figma_tanjiro.jpg',
    images: ['https://res.cloudinary.com/demo/image/upload/v1/figma_tanjiro_1.jpg'],
    stock: 14,
    inStock: true,
    rating: 4.7,
    reviewCount: 134,
    soldCount: 267,
    brand: 'Max Factory',
    series: 'Demon Slayer',
    character: 'Tanjiro Kamado',
    material: 'ABS, PVC',
    height: '14cm',
    scale: 'Non-scale',
    shortDescription: 'Articulated Figma of the water breathing user',
    description: 'Tanjiro Figma with Nichirin sword and water breathing effects.',
    tags: ['figma', 'tanjiro', 'kimetsu', 'poseable'],
    isHot: false,
    isFeatured: false,
  },

  // Scale Figures
  {
    name: 'Tamamo Cross Race Ver. 1/7',
    slug: 'tamamo-cross-race',
    sku: 'SF-001',
    price: 3250000,
    originalPrice: 3650000,
    isOnSale: true,
    thumbnail: 'https://res.cloudinary.com/demo/image/upload/v1/tamamo_cross.jpg',
    images: [
      'https://res.cloudinary.com/demo/image/upload/v1/tamamo_cross_1.jpg',
      'https://res.cloudinary.com/demo/image/upload/v1/tamamo_cross_2.jpg',
      'https://res.cloudinary.com/demo/image/upload/v1/tamamo_cross_3.jpg',
    ],
    stock: 3,
    inStock: true,
    rating: 5.0,
    reviewCount: 87,
    soldCount: 156,
    brand: 'Phat Company',
    series: 'Umamusume',
    character: 'Tamamo Cross',
    material: 'PVC, ABS',
    height: '26cm',
    scale: '1/7',
    shortDescription: 'Premium scale figure of Tamamo Cross',
    description: 'Highly detailed 1/7 scale figure of Tamamo Cross in her racing outfit. Premium quality with dynamic pose and detailed base.',
    tags: ['scale', 'umamusume', 'tamamo', 'racing'],
    isHot: true,
    isFeatured: true,
  },
  {
    name: '2B YoRHa No.2 Type B 1/7',
    slug: '2b-yorha-scale',
    sku: 'SF-002',
    price: 2850000,
    originalPrice: 3200000,
    isOnSale: true,
    thumbnail: 'https://res.cloudinary.com/demo/image/upload/v1/2b_scale.jpg',
    images: ['https://res.cloudinary.com/demo/image/upload/v1/2b_scale_1.jpg'],
    stock: 6,
    inStock: true,
    rating: 4.9,
    reviewCount: 201,
    soldCount: 378,
    brand: 'Square Enix',
    series: 'NieR:Automata',
    character: '2B',
    material: 'PVC, ABS',
    height: '25cm',
    scale: '1/7',
    shortDescription: 'Beautiful 2B figure in combat pose',
    description: 'Stunning scale figure of 2B with Virtuous Contract and Virtuous Treaty swords.',
    tags: ['2b', 'nier', 'automata', 'square-enix'],
    isHot: true,
    isFeatured: true,
  },
  {
    name: 'Zero Two Childhood Ver. 1/7',
    slug: 'zero-two-childhood',
    sku: 'SF-003',
    price: 1950000,
    originalPrice: 2200000,
    isOnSale: true,
    thumbnail: 'https://res.cloudinary.com/demo/image/upload/v1/zero_two_child.jpg',
    images: ['https://res.cloudinary.com/demo/image/upload/v1/zero_two_child_1.jpg'],
    stock: 9,
    inStock: true,
    rating: 4.6,
    reviewCount: 92,
    soldCount: 167,
    brand: 'Kotobukiya',
    series: 'Darling in the FranXX',
    character: 'Zero Two',
    material: 'PVC',
    height: '21cm',
    scale: '1/7',
    shortDescription: 'Young Zero Two with picture book',
    description: 'Scale figure of young Zero Two reading a picture book, capturing her innocent side.',
    tags: ['zero-two', 'darling', 'franxx', 'kotobukiya'],
    isHot: false,
    isFeatured: false,
  },

  // Model Kits
  {
    name: 'MEGAMI DEVICE Asra Ninja',
    slug: 'megami-device-asra',
    sku: 'MK-001',
    price: 1480000,
    originalPrice: 1650000,
    isOnSale: true,
    thumbnail: 'https://res.cloudinary.com/demo/image/upload/v1/asra_ninja.jpg',
    images: ['https://res.cloudinary.com/demo/image/upload/v1/asra_ninja_1.jpg'],
    stock: 11,
    inStock: true,
    rating: 4.7,
    reviewCount: 76,
    soldCount: 145,
    brand: 'Kotobukiya',
    series: 'Megami Device',
    character: 'Asra Ninja',
    material: 'PS, ABS, PVC',
    height: '14cm',
    scale: '1/1',
    shortDescription: 'Highly customizable ninja mecha girl kit',
    description: 'Fully articulated plastic model kit of Asra Ninja. Can be customized and posed in various ways.',
    tags: ['megami-device', 'model-kit', 'kotobukiya', 'customizable'],
    isHot: false,
    isFeatured: false,
  },
  {
    name: 'Frame Arms Girl Hresvelgr',
    slug: 'fag-hresvelgr',
    sku: 'MK-002',
    price: 1280000,
    originalPrice: 1450000,
    isOnSale: true,
    thumbnail: 'https://res.cloudinary.com/demo/image/upload/v1/hresvelgr.jpg',
    images: ['https://res.cloudinary.com/demo/image/upload/v1/hresvelgr_1.jpg'],
    stock: 13,
    inStock: true,
    rating: 4.5,
    reviewCount: 54,
    soldCount: 98,
    brand: 'Kotobukiya',
    series: 'Frame Arms Girl',
    character: 'Hresvelgr',
    material: 'PS, ABS',
    height: '15cm',
    scale: 'Non-scale',
    shortDescription: 'Flying type Frame Arms Girl kit',
    description: 'Model kit of Hresvelgr with large wings and various weapons. Highly poseable.',
    tags: ['frame-arms-girl', 'model-kit', 'mecha-girl', 'kotobukiya'],
    isHot: false,
    isFeatured: false,
  },
];

async function seed() {
  try {
    console.log('🌱 Starting seed process...');

    // Connect to MongoDB
    await connect(process.env.MONGO_URI || 'mongodb://localhost:27017/neo-figure');
    console.log('✅ Connected to MongoDB');

    // Clear existing data
    console.log('🗑️  Clearing existing data...');
    await connection.collection('categories').deleteMany({});
    await connection.collection('products').deleteMany({});
    console.log('✅ Cleared existing data');

    // Insert categories
    console.log('📦 Inserting categories...');
    const categoryResult = await connection.collection('categories').insertMany(categoryData);
    const categoryIds = Object.values(categoryResult.insertedIds);
    console.log(`✅ Inserted ${categoryIds.length} categories`);

    // Map category slugs to IDs
    const categoryMap = {};
    const categories = await connection.collection('categories').find().toArray();
    categories.forEach((cat: any) => {
      categoryMap[cat.slug] = cat._id;
    });

    // Assign categories to products
    const productsWithCategories = productData.map((product, index) => {
      let categoryId;
      if (index < 3) categoryId = categoryMap['gundam']; // First 3 are Gundam
      else if (index < 6) categoryId = categoryMap['anime-figure']; // Next 3 are Anime Figures
      else if (index < 9) categoryId = categoryMap['nendoroid']; // Next 3 are Nendoroids
      else if (index < 11) categoryId = categoryMap['figma']; // Next 2 are Figma
      else if (index < 14) categoryId = categoryMap['scale-figure']; // Next 3 are Scale Figures
      else categoryId = categoryMap['model-kit']; // Rest are Model Kits

      return { ...product, categoryId };
    });

    // Insert products
    console.log('📦 Inserting products...');
    const productResult = await connection.collection('products').insertMany(productsWithCategories);
    console.log(`✅ Inserted ${Object.keys(productResult.insertedIds).length} products`);

    console.log('🎉 Seed completed successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed failed:', error);
    process.exit(1);
  }
}

seed();
